### ISSUE TITLE
Sdk as runtime

### ISSUE THREAD

**Issue by linuxrider** [flathub/com.gitlab.cutecom.cutecom#3]
@Murmele Thank you for bringing this to flathub.
I was wondering if it is really necessary to use the `Sdk` as runtime. I tried to use `org.kde.Platform` instead and it still runs. I did no extensive testing though. Could you comment on what the reason was to go with the `Sdk`?

**Comment by Murmele** [comment]
Oh sorry this is a mistake. I will change
